### ISSUE TITLE
What about if more mentors than one mentor for a project?

### ISSUE THREAD

**Issue by ahmetbcakici** [cagataycali/find-mentor#209]

**Comment by mbugrayildiz** [comment]
How does two GitHub profiles possess the same repo tho? Sure the owner can add the other as a contributor (which literally means the other person can do anything they want) but I don't think it is possible to implement such feature. Mainly because GitHub doesn't have such capabilities, partly because some other mentor can always help the mentee in fixing bugs or implementing features without any restrictions by the former one.

Is it not reasonable or have I not understood the issue properly?
